apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: live-code:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /tasks
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /tasks
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30